config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tracks do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :playlists

  resources :playlist_tracks

  resources :invoices do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :invoice_lines do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :media_types do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :genres do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :employees do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :customers do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :artists do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :albums do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :filters, only: [:index], controller: 'tools/filters'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'home#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :customers, foreign_key: 'support_rep_id'
  belongs_to :reporting_to, class_name: 'Employee', optional: true, foreign_key: 'reports_to'
  has_many :subordinates, class_name: 'Employee', foreign_key: 'reports_to'
  has_many :invoices, through: :customers
  has_many :invoice_lines, through: :invoices
  has_many :tracks, through: :invoice_lines
  has_many :genres, through: :tracks, source: :genre
  has_many :media_types, through: :tracks, source: :media_type
  has_many :playlist_tracks, through: :tracks
  has_many :playlists, through: :playlist_tracks
  has_many :albums, through: :tracks, source: :album
  has_many :artists, through: :albums

  attr_accessor :customers_count, :subordinates_count

  validate :reports_to_is_not_self
  validates :first_name, :last_name, :address, presence: true


  scope :with_customers_count_in_range, -> (min_value, max_value = nil) {
    # use the sub query from Customer model
    query = Customer.with_record_count_by_employee_in_range_for_use_as_sub_query(min_value, max_value)
    if query.exists?
      where(id: query)
    else
      none
    end
  }

  scope :with_subordinates_count_in_range, -> (min_value, max_value = nil) {
    # use the sub query from Employee model
    with_record_count_by_manager_in_range_for_use_as_sub_query(min_value, max_value)
  }

  scope :with_record_count_by_manager_in_range_for_use_as_sub_query, ->(min_value, max_value = nil) {
    return Employee.none if min_value.nil? && max_value.nil?

    query = Employee.select(:reports_to).group(:reports_to)

    if min_value.present? && max_value.present?
      if min_value > max_value
        return Employee.none
      elsif min_value == max_value
        query = query.having('COUNT(id) = ?', min_value)
      else
        query = query.having('COUNT(id) BETWEEN ? AND ?', min_value, max_value)
      end
    elsif min_value.nil? && max_value.present?
      query = query.having('COUNT(id) <= ?', max_value)
    elsif min_value.present? && max_value.nil?
      query = query.having('COUNT(id) >= ?', min_value)
    end

    query
  }

  scope :has_customers, -> (has_customers = true) {
    sub_query = Customer.select('1').where('customers.support_rep_id = employees.id')
    if has_customers
      where('EXISTS (?)', sub_query)
    else
      where.not('EXISTS (?)', sub_query)
    end
  }

  scope :has_subordinates, -> (has_subordinates = true) {
    sub_query = Employee.select('1').where('e2.reports_to = employees.id').from(Employee.arel_table.as('e2'))
    if has_subordinates
      where('EXISTS (?)', sub_query)
    else
      where.not('EXISTS (?)', sub_query)
    end
  }


  def full_name
    [first_name, last_name].join(' ')
  end

  def to_s
    full_name
  end

  def display_customers_count
    customers_count || customers.count
  end

  def display_subordinates_count
    subordinates_count || subordinates.count
  end

  def reports_to_is_not_self
    if reports_to == self
      errors.add(:reports_to, 'cannot be self')
    end
  end


  class << self

    def display_columns
      [
        'id', 'first_name', 'last_name', 'title',
        'address', 'city', 'state', 'postal_code', 'country', 'phone', 'fax', 'email',
        'display_customers_count', 'display_subordinates_count',
        {
          field: 'reporting_to',
          type: 'association',
        },
        'birth_date', 'hire_date',
        'created_at', 'updated_at'
      ]
    end

    def ransackable_attributes(auth_object = nil)
      ['id', 'first_name', 'last_name', 'title', 'reports_to', 'birth_date', 'hire_date', 'address', 'city', 'state', 'country', 'postal_code', 'phone', 'fax', 'email', 'created_at', 'updated_at']
    end

    def ransackable_associations(auth_object = nil)
      ['customers', 'reporting_to', 'subordinates', 'invoices', 'invoice_lines', 'tracks', 'genres', 'media_types', 'playlist_tracks', 'playlists', 'albums', 'artists']
    end
    
    def count_by_manager_ids(ids)
      column_name = 'reports_to'
      if column_names.include?(column_name)
        Employee.where(column_name => ids).group(column_name).count
      else
        {}
      end
    end

    def employees_ids_with_most_subordinates(has_more_than_subordinates = 5)
      Employee.group(:reports_to).having('count_id >= ?', has_more_than_subordinates_count).count('id')
    end

    def first_of_employees_ids_with_most_subordinates
      employees_ids_with_most_subordinates&.keys.first
    end

    def last_of_employees_ids_with_most_subordinates
      employees_ids_with_most_subordinates&.keys.last
    end


    def employees_ids_with_fewest_subordinates(has_fewer_than_subordinates = 5)
      Employee.group(:reports_to).having('count_id <= ?', has_fewer_than_subordinates).count('id')
    end

    def first_of_employees_ids_with_fewest_subordinates
      employees_ids_with_fewest_subordinates&.keys.first
    end

    def last_of_employees_ids_with_fewest_subordinates
      employees_ids_with_fewest_subordinates&.keys.last
    end


    def employees_ids_with_most_customers(has_more_than_customers = 5)
      Customer.group(:support_rep_id).having('count_id >= ?', has_more_than_customers).count('id')
    end

    def first_of_employees_ids_with_most_customers
      employees_ids_with_most_customers&.keys.first
    end

    def last_of_employees_ids_with_most_customers
      employees_ids_with_most_customers&.keys.last
    end


    def employees_ids_with_fewest_customers(has_fewer_than_customers = 5)
      Customer.group(:support_rep_id).having('count_id <= ?', has_fewer_than_customers).count('id')
    end

    def first_of_employees_ids_with_fewest_customers
      employees_ids_with_fewest_customers&.keys.first
    end

    def last_of_employees_ids_with_fewest_customers
      employees_ids_with_fewest_customers&.keys.last
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include Filterable
  include Sortable
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    begin
      @pagy, @employees = process_filters(model_query)
    rescue => e
      if e.is_a?(Pagy::OverflowError)
        @pagy = Pagy.new(count: 0)
        @employees = Employee.none
      else
        raise e
      end
    end

    if @employees.present?
      customers_count = Customer.count_by_employee_ids(@employees.pluck(:id))
      subordinates_count = Employee.count_by_manager_ids(@employees.pluck(:id))
      @employees.each do |employee|
        employee.customers_count = customers_count[employee.id] || 0
        employee.subordinates_count = subordinates_count[employee.id] || 0
      end
    end

    render_index('table')
  end

  def json_list_for_select_element
    _, employees = pagy(Employee.ransack(first_name_or_last_name_cont: params[:keyword]).result)
    employees = employees.map do |employee|
      { value: employee.id, label: employee.full_name }
    end
    render json: employees
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_path, status: :see_other, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:last_name, :first_name, :email, :title, :reports_to, :birth_date, :hire_date, :address, :city, :state, :country, :postal_code, :phone, :fax)
    end
    
    def default_ransack_params
      :first_name_or_last_name_or_address_or_phone_or_email_cont
    end

    def model_query
      if is_sort_by_reporting_to?
        Employee.left_joins(:reporting_to).preload(:reporting_to)
      elsif is_sort_by_customers_count?
        Employee.includes(:reporting_to).left_joins(:customers).group('employees.id')
      elsif is_sort_by_subordinates_count?
        Employee.includes(:reporting_to).left_joins(:subordinates).group('employees.id')
      else
        Employee.includes(:reporting_to)
      end
    end

    def is_sort_by_reporting_to?
      @is_sort_by_reporting_to ||= (sort_column == 'reporting_to')
    end

    def is_sort_by_customers_count?
      @is_sort_by_customers_count ||= (sort_column == 'customers_count')
    end

    def is_sort_by_subordinates_count?
      @is_sort_by_subordinates_count ||= (sort_column == 'subordinates_count')
    end

    def sorting_params
      if is_sort_by_reporting_to?
        {
          'reporting_tos_employees.first_name' => sort_direction,
          'reporting_tos_employees.last_name' => sort_direction
        }
      elsif is_sort_by_customers_count?
        "COUNT(customers.id) #{sort_direction}"
      elsif is_sort_by_subordinates_count?
        "COUNT(subordinates_employees.id) #{sort_direction}"
      else
        super
      end
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<%= render 'shared/display_record', record: employee do %>
  <%= render_columns(employee) do |column, value| %>
    <% if column[:field] == 'reporting_to' %>
      <% if employee.reporting_to %>
        <strong><%= Employee.human_attribute_name('reports_to') %>:</strong> <%= link_to employee.reporting_to %>
      <% elsif employee.reports_to.present? %>
        <strong><%= Employee.human_attribute_name('manager_id') %>:</strong> <%= employee.reports_to %>
      <% else %>
        <strong><%= Employee.human_attribute_name('manager_id') %>:</strong> <%= Employee.human_attribute_name('no_manager') %>
      <% end %>
    <% else %>
      <% render_default(column, value, employee) %>
    <% end %>
  <% end %>
<% end %>

app/views/employees/_form.html.erb
<%= render 'shared/record_form', record: employee %>

app/views/employees/_table.html.erb
<style>
  .invoice-lines-table {
    min-height: 300px;
  }
  .employee-address {
    min-width: 300px;
  }
</style>

<% turbo_confirm = translate('actions.confirm_destroy', model: Employee.model_name.human.downcase, count: 1) %>

<div class='mb-4 employees-table table-responsive'>
  <table class='table table-bordered table-striped table-hover'>
    <thead class='thead-light'>
      <tr>
        <th colspan='2' class='text-center'><%= Employee.human_attribute_name('personal_information') %></th>
        <th class='text-center'><%= Employee.human_attribute_name('address') %></th>
        <th colspan='2' class='text-center'><%= Employee.human_attribute_name('contact_information') %></th>
        <th colspan='3' class='text-center'><%= Employee.human_attribute_name('other_information') %></th>
        <th></th>
      </tr>
      <tr>
        <th class='text-nowrap'>
          <%= build_sort_link('first_name', Employee) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('last_name', Employee) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('address', Employee) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('phone', Employee) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('email', Employee) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('reporting_to', Employee) %>
        </th>
        <th class='text-nowrap'><%= Employee.human_attribute_name('display_customers_count') %></th>
        <th class='text-nowrap'><%= Employee.human_attribute_name('title_timestamp') %></th>
        <th class='text-center text-nowrap'><%= translate('base.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= link_to employee.first_name, employee %></td>
          <td><%= link_to employee.last_name, employee %></td>

          <td class='employee-address'>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownAddress<%= employee.id %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= employee.address %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownAddress<%= employee.id %>'>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('state') %>:</strong> <%= employee.state %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('city') %>:</strong> <%= employee.city %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('postal_code') %>:</strong> <%= employee.postal_code %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('country') %>:</strong> <%= employee.country %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('address') %>:</strong> <%= employee.address %></li>
              </ul>
            </div>
          </td>

          <td>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownPhone<%= employee.id %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= employee.phone %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownPhone<%= employee.id %>'>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('fax') %>:</strong> <%= employee.fax %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('phone') %>:</strong> <%= employee.phone %></li>
              </ul>
            </div>
          </td>
          <td><%= employee.email %></td>
          
          <td class='text-nowrap'>
						<%= Employee.human_attribute_name('reports_to') %>: <%= employee.reporting_to&.full_name %>
						<br/>
						<%= Employee.human_attribute_name('display_subordinates_count') %>: <%= employee.display_subordinates_count %>
					</td>
          <td><%= link_to employee.display_customers_count, employee %></td>
          <td>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownOtherInfo<%= employee.id %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= employee.title %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownOtherInfo<%= employee.id %>'>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('title') %>:</strong> <%= employee.title %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('birth_date') %>:</strong> <%= employee.birth_date %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('hire_date') %>:</strong> <%= employee.hire_date %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('created_at') %>:</strong> <%= employee.created_at %></li>
                <li class='px-3 text-nowrap'><strong><%= Employee.human_attribute_name('updated_at') %>:</strong> <%= employee.updated_at %></li>
                <li class='px-3 text-nowrap'><strong><%= link_to Employee.human_attribute_name('view_employee'), employee %></strong></li>
              </ul>
            </div>
          </td>

          <td class='text-center'>
            <div class='dropdown'>
              <button class='btn btn-secondary btn-sm dropdown-toggle'
                type='button' id='dropdownActions<%= employee.id %>'
                data-bs-toggle='dropdown' aria-expanded='false'>
                <%= translate('base.actions') %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownActions<%= employee.id %>'>
                <li>
                  <%= link_to employee, class: 'dropdown-item' do %>
                    <i class='bi bi-eye'></i> <%= translate('actions.view') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_employee_path(employee), class: 'dropdown-item text-warning' do %>
                    <i class='bi bi-pencil'></i> <%= translate('actions.edit') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to employee, method: :delete,
                    data: { turbo_method: 'delete', turbo_confirm: turbo_confirm },
                    class: 'dropdown-item text-danger' do %>
                    <i class='bi bi-trash'></i> <%= translate('actions.delete') %>
                  <% end %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/edit.html.erb
<%= render 'shared/header_form', record: @employee %>

<%= render 'shared/record_form', record: @employee %>

<%= render 'shared/footer_actions', record: @employee %>

app/views/employees/index.html.erb
<div style='color: green'><%= notice %></div>

<%= render 'shared/index_header', mode: 'table' %>

<%= render 'shared/filter_form', filter_model: 'Employee' %>

<%= render 'shared/index_records', mode: 'table' %>

<%= link_to translate('base.new_record', model: Employee.model_name.human.downcase), new_employee_path, class: 'btn btn-primary' %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form', employee: @employee %>

<br>

<div>
  <%= link_to 'Back to employees', employees_path %>
</div>

app/views/employees/show.html.erb
<p style='color: green'><%= notice %></p>

<%= render @employee %>