config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tracks do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :playlists

  resources :playlist_tracks

  resources :invoices do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :invoice_lines do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :media_types do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :genres do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :employees do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :customers do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :artists do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :albums do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :filters, only: [:index], controller: 'tools/filters'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'home#index'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :invoice_lines
  has_many :tracks, through: :invoice_lines
  has_many :playlist_tracks, through: :tracks
  has_many :playlists, through: :playlist_tracks
  has_many :genres, through: :tracks, source: :genre
  has_many :media_types, through: :tracks, source: :media_type
  has_many :albums, through: :tracks, source: :album
  has_many :artists, through: :albums
  has_one :support_rep, through: :customer

  attr_accessor :invoice_lines_count

  validates :invoice_date, :billing_address, :billing_city, :billing_state, :billing_country, :billing_postal_code, presence: true


  scope :with_record_count_by_customer_in_range_for_use_as_sub_query, ->(min_value, max_value = nil) {
    return Invoice.none if min_value.nil? && max_value.nil?

    query = Invoice.select(:customer_id).group(:customer_id)

    if min_value.present? && max_value.present?
      if min_value > max_value
        return Invoice.none
      elsif min_value == max_value
        query = query.having('COUNT(id) = ?', min_value)
      else
        query = query.having('COUNT(id) BETWEEN ? AND ?', min_value, max_value)
      end
    elsif min_value.nil? && max_value.present?
      query = query.having('COUNT(id) <= ?', max_value)
    elsif min_value.present? && max_value.nil?
      query = query.having('COUNT(id) >= ?', min_value)
    end

    query
  }

  scope :with_invoice_lines_count_in_range, -> (min_value, max_value = nil) {
    # use the sub query from InvoiceLine model
    query = InvoiceLine.with_record_count_by_invoice_in_range_for_use_as_sub_query(min_value, max_value)
    if query.exists?
      where(id: query)
    else
      Invoice.none
    end
  }


  def total_price
    invoice_lines.pluck(:unit_price).sum
  end

  def to_s
    "#{self.class.human_attribute_name('id')}: #{id}"
  end

  def display_invoice_lines_count
    invoice_lines_count || invoice_lines.count
  end


  class << self

    def display_columns
      [
        'id',
        {
          field: 'customer',
          type: 'association',
        },
        'invoice_date', 'billing_address', 'billing_city', 'billing_state',
        'billing_postal_code', 'billing_country', 'total', 'display_invoice_lines_count',
        'created_at', 'updated_at'
      ]
    end

    def ransackable_attributes(auth_object = nil)
      ['id', 'customer_id', 'invoice_date', 'billing_address', 'billing_city', 'billing_state', 'billing_country', 'billing_postal_code', 'total', 'created_at', 'updated_at']
    end

    def ransackable_associations(auth_object = nil)
      ['customer', 'invoice_lines', 'tracks', 'playlist_tracks', 'playlists', 'genres', 'media_types', 'albums', 'artists', 'support_rep']
    end
    
    def count_by_model_ids(model, ids)
      column_name = "#{model.to_s.singularize}_id"
      if column_names.include?(column_name)
        Invoice.where(column_name => ids).group(column_name).count
      else
        {}
      end
    end

    def count_tracks_by_invoice_ids(invoice_ids)
      Invoice.joins(invoice_lines: :track).where(id: invoice_ids).group('invoices.id').count
    end

    def customers_ids_with_most_invoices(has_more_than_invoices_or_equal_to = 7)
      Invoice.group(:customer_id).having("count_id >= #{has_more_than_invoices_or_equal_to}").order('count_id desc').count('id')
    end

    def first_of_most_invoiced_customer_id(has_more_than_invoices_or_equal_to = 7)
      customers_ids_with_most_invoices(has_more_than_invoices_or_equal_to)&.keys.first
    end

    def last_of_most_invoiced_customer_id(has_more_than_invoices_or_equal_to = 7)
      customers_ids_with_most_invoices(has_more_than_invoices_or_equal_to)&.keys.last
    end


    def customers_ids_with_fewest_invoices(has_less_than_invoices_or_equal_to = 5)
      Invoice.group(:customer_id).having("count_id <= #{has_less_than_invoices_or_equal_to}").order('count_id desc').count('id')
    end

    def first_of_fewest_invoiced_customer_id(has_less_than_invoices_or_equal_to = 5)
      customers_ids_with_fewest_invoices(has_less_than_invoices_or_equal_to)&.keys.first
    end

    def last_of_fewest_invoiced_customer_id(has_less_than_invoices_or_equal_to = 5)
      customers_ids_with_fewest_invoices(has_less_than_invoices_or_equal_to)&.keys.last
    end


    def invoice_ids_with_most_tracks(has_more_than_tracks_or_equal_to = 5)
      Invoice.joins(:invoice_lines).group('invoices.id').
        having("count_invoice_lines_id >= #{has_more_than_tracks_or_equal_to}").
        order('count_invoice_lines_id desc').
        count('invoice_lines.id')
    end

    def first_of_most_tracks_invoice_id(has_more_than_tracks_or_equal_to = 5)
      invoice_ids_with_most_tracks(has_more_than_tracks_or_equal_to)&.keys.first
    end

    def last_of_most_tracks_invoice_id(has_more_than_tracks_or_equal_to = 5)
      invoice_ids_with_most_tracks(has_more_than_tracks_or_equal_to)&.keys.last
    end


    def invoice_ids_with_fewest_tracks(has_less_than_tracks_or_equal_to = 5)
      Invoice.joins(:invoice_lines).group('invoices.id').
        having("count_invoice_lines_id <= #{has_less_than_tracks_or_equal_to}").
        order('count_invoice_lines_id desc').
        count('invoice_lines.id')
    end

    def first_of_fewest_tracks_invoice_id(has_less_than_tracks_or_equal_to = 5)
      invoice_ids_with_fewest_tracks(has_less_than_tracks_or_equal_to)&.keys.first
    end

    def last_of_fewest_tracks_invoice_id(has_less_than_tracks_or_equal_to = 5)
      invoice_ids_with_fewest_tracks(has_less_than_tracks_or_equal_to)&.keys.last
    end


    def top_most_expensive_invoice_ids(limit = 5)
      Invoice.joins(:invoice_lines).
        group('invoices.id').
        order('sum_unit_price DESC').
        limit(limit).sum('unit_price')
    end

    def first_of_top_most_expensive_invoice_ids(limit = 5)
      top_most_expensive_invoice_ids(limit)&.keys.first
    end

    def last_of_top_most_expensive_invoice_ids(limit = 5)
      top_most_expensive_invoice_ids(limit)&.keys.last
    end


    def top_fewest_expensive_invoice_ids(limit = 5)
      Invoice.joins(:invoice_lines).
        group('invoices.id').
        order('sum_unit_price ASC').
        limit(limit).sum('unit_price')
    end

    def first_of_top_fewest_expensive_invoice_ids(limit = 5)
      top_fewest_expensive_invoice_ids(limit)&.keys.first
    end

    def last_of_top_fewest_expensive_invoice_ids(limit = 5)
      top_fewest_expensive_invoice_ids(limit)&.keys.last
    end


    def invoices_ids_with_number_of_invoice_lines_between(min_value, max_value = nil)
      return {} if min_value.nil? && max_value.nil?

      query = Invoice.joins(:invoice_lines).group('invoices.id')

      if min_value.present? && max_value.present?
        if min_value > max_value
          return {}
        elsif min_value == max_value
          query = query.having('count_invoice_lines_id = ?', min_value)
        else
          query = query.having('count_invoice_lines_id BETWEEN ? AND ?', min_value, max_value)
        end
      elsif min_value.nil? && max_value.present?
        query = query.having('count_invoice_lines_id <= ?', max_value)
      elsif min_value.present? && max_value.nil?
        query = query.having('count_invoice_lines_id >= ?', min_value)
      end

      query.count('invoice_lines.id')
    end


    def invoices_ids_with_total_price_between(min_value, max_value = nil)
      return {} if min_value.nil? && max_value.nil?

      query = Invoice.joins(:invoice_lines).group('invoices.id')

      if min_value.present? && max_value.present?
        if min_value > max_value
          return {}
        elsif min_value == max_value
          query = query.having('sum_unit_price = ?', min_value)
        else
          query = query.having('sum_unit_price BETWEEN ? AND ?', min_value, max_value)
        end
      elsif min_value.nil? && max_value.present?
        query = query.having('sum_unit_price <= ?', max_value)
      elsif min_value.present? && max_value.nil?
        query = query.having('sum_unit_price >= ?', min_value)
      end

      query.sum('unit_price')
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  include Filterable
  include Sortable
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    begin
      @pagy, @invoices = process_filters(model_query)
    rescue => e
      if e.is_a?(Pagy::OverflowError)
        @pagy = Pagy.new(count: 0)
        @invoices = Invoice.none
      else
        raise e
      end
    end

    if @invoices.present?
      invoice_lines_count = InvoiceLine.count_by_model_ids(:invoice, @invoices.pluck(:id))
      @invoices.each do |invoice|
        invoice.invoice_lines_count = invoice_lines_count[invoice.id] || 0
      end
    end

    render_index('table')
  end

  def json_list_for_select_element
    query = params[:keyword].to_s.strip
    if query.match?(/^\d+$/) # search by id
      result = Invoice.includes(:customer).where('CAST(id AS TEXT) LIKE ?', "%#{query}%")
    else
      result = Invoice.includes(:customer).ransack(customer_first_name_or_customer_last_name_cont: query).result
    end

    _, invoices = pagy(result)
    invoices = invoices.map do |invoice|
      { value: invoice.id, label: "ID: #{invoice.id} - By: #{invoice.customer&.full_name}" }
    end
    render json: invoices
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy!

    respond_to do |format|
      format.html { redirect_to invoices_path, status: :see_other, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:customer_id, :invoice_date, :billing_address, :billing_city, :billing_state, :billing_country, :billing_postal_code, :total)
    end


    def default_ransack_params
      :billing_address_or_billing_postal_code_or_customer_first_name_or_customer_last_name_cont
    end

    def model_query
      if is_sort_by_customer?
        Invoice.left_joins(:customer).preload(:customer)
      elsif is_sort_by_invoice_lines_count?
        Invoice.includes(:customer).left_joins(:invoice_lines).group('invoices.id')
      else
        Invoice.includes(:customer)
      end
    end

    def is_sort_by_customer?
      @is_sort_by_customer ||= (sort_column == 'customer')
    end

    def is_sort_by_invoice_lines_count?
      @is_sort_by_invoice_lines_count ||= (sort_column == 'invoice_lines_count')
    end

    def sorting_params
      if is_sort_by_customer?
        {
          'customers.first_name' => sort_direction,
          'customers.last_name' => sort_direction
        }
      elsif is_sort_by_invoice_lines_count?
        "COUNT(invoice_lines.id) #{sort_direction}"
      else
        super
      end
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= render 'shared/record_form', record: invoice %>

app/views/invoices/_invoice.html.erb
<%= render 'shared/display_record', record: invoice do %>
  <%= render_columns(invoice) do |column, value| %>
    <% if column[:field] == 'customer' %>
      <% if invoice.customer %>
        <strong>Customer:</strong> <%= link_to invoice.customer.full_name, invoice.customer %>
      <% elsif invoice.customer_id.present? %>
        <strong>Customer:</strong> <%= invoice.customer_id %>
      <% else %>
        <strong>Customer:</strong> Missing customer
      <% end %>
    <% else %>
      <% render_default(column, value, invoice) %>
    <% end %>
  <% end %>
<% end %>

app/views/invoices/_table.html.erb
<style>
  .invoices-table {
    min-height: 300px;
  }
  .invoice-customer {
    min-width: 200px;
  }
  .invoice-billing-address {
    min-width: 300px;
  }
</style>

<% turbo_confirm = translate('actions.confirm_destroy', model: Invoice.model_name.human.downcase, count: 1) %>

<div class='mb-4 invoices-table table-responsive'>
  <table class='table table-bordered table-striped table-hover'>
    <thead class='thead-light'>
      <tr>
        <th class='text-nowrap'>
          <%= build_sort_link('id', Invoice) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('invoice_date', Invoice) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('customer', Invoice) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('total', Invoice) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('billing_address', Invoice) %>
        </th>
        <th class='text-nowrap'><%= Invoice.human_attribute_name('display_invoice_lines_count') %></th>
        <th class='text-center text-nowrap'><%= translate('base.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= link_to invoice %></td>
          <td><%= link_to invoice.invoice_date, invoice %></td>
          
          <td class='invoice-customer'>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownCustomer<%= invoice.id %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= invoice.customer&.full_name %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownCustomer<%= invoice.id %>'>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('company') %>:</strong> <%= invoice.customer&.company %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('address') %>:</strong> <%= invoice.customer&.address %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('city') %>:</strong> <%= invoice.customer&.city %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('state') %>:</strong> <%= invoice.customer&.state %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('country') %>:</strong> <%= invoice.customer&.country %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('phone') %>: </strong> <%= invoice.customer&.phone %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('fax') %>: </strong> <%= invoice.customer&.fax %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('email') %>: </strong> <%= invoice.customer&.email %></li>
                <li class='px-3 text-nowrap'><strong><%= Customer.human_attribute_name('full_name') %>: </strong> <%= invoice.customer&.full_name %></li>
                <li class='px-3 text-nowrap'><strong><%= link_to Customer.human_attribute_name('view_customer'), invoice.customer %></strong></li>
              </ul>
            </div>
          </td>

          <td class='text-nowrap'><%= render_decimal_value(invoice.total) %></td>

          <td class='invoice-billing-address'>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownAddress<%= invoice.id %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= invoice.billing_address %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownAddress<%= invoice.id %>'>
                <li class='px-3 text-nowrap'><strong><%= Invoice.human_attribute_name('billing_city') %>: </strong> <%= invoice.billing_city %></li>
                <li class='px-3 text-nowrap'><strong><%= Invoice.human_attribute_name('billing_state') %>: </strong> <%= invoice.billing_state %></li>
                <li class='px-3 text-nowrap'><strong><%= Invoice.human_attribute_name('billing_country') %>: </strong> <%= invoice.billing_country %></li>
                <li class='px-3 text-nowrap'><strong><%= Invoice.human_attribute_name('billing_postal_code') %>: </strong> <%= invoice.billing_postal_code %></li>
                <li class='px-3 text-nowrap'><strong><%= Invoice.human_attribute_name('billing_address') %>: </strong> <%= invoice.billing_address %></li>
              </ul>
            </div>
          </td>

          <td class='text-nowrap'><%= link_to invoice.display_invoice_lines_count, invoice %></td>

          <td class='text-center'>
            <div class='dropdown'>
              <button class='btn btn-secondary btn-sm dropdown-toggle'
                type='button' id='dropdownActions<%= invoice.id %>'
                data-bs-toggle='dropdown' aria-expanded='false'>
                <%= translate('base.actions') %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownActions<%= invoice.id %>'>
                <li>
                  <%= link_to invoice, class: 'dropdown-item' do %>
                    <i class='bi bi-eye'></i> <%= translate('actions.view') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_invoice_path(invoice), class: 'dropdown-item text-warning' do %>
                    <i class='bi bi-pencil'></i> <%= translate('actions.edit') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to invoice, method: :delete,
                    data: { turbo_method: 'delete', turbo_confirm: turbo_confirm },
                    class: 'dropdown-item text-danger' do %>
                    <i class='bi bi-trash'></i> <%= translate('actions.delete') %>
                  <% end %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/edit.html.erb
<%= render 'shared/header_form', record: @invoice %>

<%= render 'shared/record_form', record: @invoice %>

<%= render 'shared/footer_actions', record: @invoice %>

app/views/invoices/index.html.erb
<div style='color: green'><%= notice %></div>

<%= render 'shared/index_header', mode: 'table' %>

<%= render 'shared/filter_form', filter_model: 'Invoice' %>

<%= render 'shared/index_records', mode: 'table' %>

<%= link_to translate('base.new_record', model: Invoice.model_name.human.downcase), new_invoice_path, class: 'btn btn-primary' %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form', invoice: @invoice %>

<br>

<div>
  <%= link_to 'Back to invoices', invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style='color: green'><%= notice %></p>

<%= render @invoice %>