config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tracks do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :playlists

  resources :playlist_tracks

  resources :invoices do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :invoice_lines do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :media_types do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :genres do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :employees do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :customers do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :artists do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :albums do
    collection do
      get :json_list_for_select_element
    end
  end

  resources :filters, only: [:index], controller: 'tools/filters'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'home#index'
end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
  belongs_to :invoice
  belongs_to :track
  has_one :customer, through: :invoice
  has_one :support_rep, through: :customer
  has_one :album, through: :track
  has_one :artist, through: :album
  has_one :genre, through: :track
  has_one :media_type, through: :track
  has_many :playlist_tracks, through: :track
  has_many :playlists, through: :playlist_tracks

  validates :unit_price, :quantity, presence: true


  scope :with_record_count_by_invoice_in_range_for_use_as_sub_query, ->(min_value, max_value = nil) {
    return InvoiceLine.none if min_value.nil? && max_value.nil?

    column_name = "#{model.to_s.singularize}_id"
    query = InvoiceLine.select(:invoice_id).group(:invoice_id)

    if min_value.present? && max_value.present?
      if min_value > max_value
        return InvoiceLine.none
      elsif min_value == max_value
        query = query.having('COUNT(id) = ?', min_value)
      else
        query = query.having('COUNT(id) BETWEEN ? AND ?', min_value, max_value)
      end
    elsif min_value.nil? && max_value.present?
      query = query.having('COUNT(id) <= ?', max_value)
    elsif min_value.present? && max_value.nil?
      query = query.having('COUNT(id) >= ?', min_value)
    end

    query
  }

  scope :with_record_count_by_track_in_range_for_use_as_sub_query, ->(min_value, max_value) {
    with_record_count_by_model_in_range_for_use_as_sub_query(:track, min_value, max_value)
  }

  scope :with_record_count_by_invoice_in_range_for_use_as_sub_query, ->(min_value, max_value) {
    with_record_count_by_model_in_range_for_use_as_sub_query(:invoice, min_value, max_value)
  }
  
  scope :with_record_count_by_model_in_range_for_use_as_sub_query, ->(model, min_value, max_value = nil) {
    return InvoiceLine.none if min_value.nil? && max_value.nil?

    column_name = "#{model.to_s.singularize}_id"
    query = InvoiceLine.select(column_name).group(column_name)

    if min_value.present? && max_value.present?
      if min_value > max_value
        return InvoiceLine.none
      elsif min_value == max_value
        query = query.having('COUNT(id) = ?', min_value)
      else
        query = query.having('COUNT(id) BETWEEN ? AND ?', min_value, max_value)
      end
    elsif min_value.nil? && max_value.present?
      query = query.having('COUNT(id) <= ?', max_value)
    elsif min_value.present? && max_value.nil?
      query = query.having('COUNT(id) >= ?', min_value)
    end

    query
  }

  scope :by_customer_ids, ->(ids) {
    where(invoice_id: Invoice.where(customer_id: ids).select(:id))
  }

  scope :by_customer_name, ->(name) {
    # where(invoice_id: Invoice.where(customer_id: Customer.where('first_name ILIKE ? OR last_name ILIKE ?', "%#{name}%", "%#{name}%").select(:id)).select(:id))
    joins(:customer)
    .ransack(customer_first_name_or_last_name_cont: name)
    .result
  }


  def total_price
    unit_price * quantity
  end

  def to_s
    "#{self.class.human_attribute_name('id')}: #{id}"
  end


  class << self

    def display_columns
      [
        'id',
        {
          field: 'invoice',
          type: 'association',
        },
        {
          field: 'track',
          type: 'association',
        },
        'unit_price', 'quantity', 'total_price',
        'created_at', 'updated_at'
      ]
    end

    def ransackable_attributes(auth_object = nil)
      ['id', 'invoice_id', 'track_id', 'unit_price', 'quantity', 'created_at', 'updated_at']
    end

    def ransackable_associations(auth_object = nil)
      ['invoice', 'track', 'customer', 'support_rep', 'album', 'artist', 'genre', 'media_type', 'playlist_tracks', 'playlists']
    end

    def count_by_model_ids(model, ids)
      column_name = "#{model.to_s.singularize}_id"
      if column_names.include?(column_name)
        InvoiceLine.where(column_name => ids).group(column_name).count
      else
        {}
      end
    end
  end
end

app/controllers/invoice_lines_controller.rb
class InvoiceLinesController < ApplicationController
  include Filterable
  include Sortable
  before_action :set_invoice_line, only: %i[ show edit update destroy ]

  # GET /invoice_lines or /invoice_lines.json
  def index
    begin
      @pagy, @invoice_lines = process_filters(model_query)
    rescue => e
      if e.is_a?(Pagy::OverflowError)
        @pagy = Pagy.new(count: 0)
        @invoice_lines = InvoiceLine.none
      else
        raise e
      end
    end

    render_index('table')
  end

  def json_list_for_select_element
    query = params[:keyword].to_s.strip
    if query.match?(/^\d+$/) # search by id
      result = InvoiceLine.includes(:customer).where('CAST(id AS TEXT) LIKE ?', "%#{query}%")
    else
      result = InvoiceLine.includes(:customer).ransack(invoice_customer_first_name_or_invoice_customer_last_name_cont: query).result
    end

    _, invoice_lines = pagy(result)
    invoice_lines = invoice_lines.map do |invoice_line|
      { value: invoice_line.id, label: "ID: #{invoice_line.id} - By: #{invoice_line.invoice&.customer&.full_name}" }
    end
    render json: invoice_lines
  end

  # GET /invoice_lines/1 or /invoice_lines/1.json
  def show
  end

  # GET /invoice_lines/new
  def new
    @invoice_line = InvoiceLine.new
  end

  # GET /invoice_lines/1/edit
  def edit
  end

  # POST /invoice_lines or /invoice_lines.json
  def create
    @invoice_line = InvoiceLine.new(invoice_line_params)

    respond_to do |format|
      if @invoice_line.save
        format.html { redirect_to @invoice_line, notice: "Invoice line was successfully created." }
        format.json { render :show, status: :created, location: @invoice_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_lines/1 or /invoice_lines/1.json
  def update
    respond_to do |format|
      if @invoice_line.update(invoice_line_params)
        format.html { redirect_to @invoice_line, notice: "Invoice line was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_lines/1 or /invoice_lines/1.json
  def destroy
    @invoice_line.destroy!

    respond_to do |format|
      format.html { redirect_to invoice_lines_path, status: :see_other, notice: "Invoice line was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_line
      @invoice_line = InvoiceLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_line_params
      params.require(:invoice_line).permit(:invoice_id, :track_id, :unit_price, :quantity)
    end


    def default_ransack_params
      :track_name_or_invoice_customer_first_name_or_invoice_customer_last_name_cont
    end

    def model_query
      if is_sort_by_track?
        InvoiceLine.left_joins(:track).preload(track: [{ album: :artist }, :genre, :media_type], invoice: [:customer])
      else
        InvoiceLine.includes(track: [{ album: :artist }, :genre, :media_type], invoice: [:customer])
      end
    end

    def is_sort_by_track?
      @is_sort_by_track ||= (sort_column == 'track')
    end

    def is_sort_by_total_price?
      @is_sort_by_total_price ||= (params[:sort]&.downcase == 'total_price')
    end

    def sorting_params
      if is_sort_by_track?
        {
          'tracks.name' => sort_direction,
        }
      elsif is_sort_by_total_price?
        sort_direction = params[:direction] || 'desc'

        Arel.sql("unit_price * quantity #{sort_direction}")
      else
        super
      end
    end
end

app/helpers/invoice_lines_helper.rb
module InvoiceLinesHelper
end

app/views/invoice_lines/_form.html.erb
<%= render 'shared/record_form', record: invoice_line %>

app/views/invoice_lines/_invoice_line.html.erb
<%= render 'shared/display_record', record: invoice_line do %>
  <%= render_columns(invoice_line) %>
<% end %>

app/views/invoice_lines/_table.html.erb
<style>
  .invoice-lines-table {
    min-height: 300px;
  }
  .track-name {
    min-width: 300px;
  }
</style>

<% turbo_confirm = translate('actions.confirm_destroy', model: InvoiceLine.model_name.human.downcase, count: 1) %>

<div class='mb-4 invoice-lines-table table-responsive'>
  <table class='table table-bordered table-striped table-hover'>
    <thead class='thead-light'>
      <tr>
        <th class='text-nowrap'>
          <%= build_sort_link('id', InvoiceLine) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('invoice_id', InvoiceLine) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('track', InvoiceLine) %>
        </th>
        <th class='text-nowrap'>
          <%= build_sort_link('total_price', InvoiceLine) %>
        </th>
        <th class='text-center text-nowrap'><%= translate('base.actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @invoice_lines.each do |invoice_line| %>
        <tr>
          <td>
            <%= link_to invoice_line %>
          </td>
          <td>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownInvoice<%= "#{invoice_line.id}" %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= invoice_line.invoice.to_s %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownInvoice<%= "#{invoice_line.id}" %>'>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('invoice_id') %>:</strong> <%= invoice_line.invoice_id %></li>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('customer') %>: </strong> <%= invoice_line.invoice&.customer&.full_name %></li>
                <li class='px-3 text-nowrap'><strong><%= link_to InvoiceLine.human_attribute_name('view_invoice'), invoice_line.invoice %></strong></li>
              </ul>
            </div>
          </td>
          <td class='track-name'>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownTrack<%= "#{invoice_line.id}" %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= invoice_line.track&.name %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownTrack<%= "#{invoice_line.id}-#{invoice_line.track_id}" %>'>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('track') %>:</strong> <%= invoice_line.track&.name %></li>
                <li class='px-3 text-nowrap'><strong><%= Track.human_attribute_name('artist') %>:</strong> <%= invoice_line.track&.album&.artist&.name %></li>
                <li class='px-3 text-nowrap'><strong><%= Track.human_attribute_name('album') %>:</strong> <%= invoice_line.track&.album&.title %></li>
                <li class='px-3 text-nowrap'><strong><%= Track.human_attribute_name('genre') %>:</strong> <%= invoice_line.track&.genre&.name %></li>
                <li class='px-3 text-nowrap'><strong><%= Track.human_attribute_name('media_type') %>:</strong> <%= invoice_line.track&.media_type&.name %></li>
                <li class='px-3 text-nowrap'><strong><%= Track.human_attribute_name('composer') %>:</strong> <%= invoice_line.track&.composer %></li>
                <li class='px-3 text-nowrap'><strong><%= link_to InvoiceLine.human_attribute_name('view_track'), invoice_line.track %></strong></li>
              </ul>
            </div>
          </td>
          <td>
            <div class='dropdown'>
              <button class='btn btn-link text-dark btn-sm dropdown-toggle text-decoration-none px-0'
                type='button' id='dropdownTotal<%= "#{invoice_line.id}" %>'
                data-bs-toggle='dropdown' aria-expanded='false' data-bs-auto-close='outside'>
                <%= render_decimal_value(invoice_line.total_price) %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownTotal<%= "#{invoice_line.id}" %>'>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('quantity') %>:</strong> <%= invoice_line.quantity %></li>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('unit_price') %>:</strong> <%= invoice_line.unit_price %></li>
                <li class='px-3 text-nowrap'><strong><%= InvoiceLine.human_attribute_name('total_price') %>:</strong> <%= render_decimal_value(invoice_line.total_price) %></li>
                <li class='px-3 text-nowrap'><strong><%= link_to InvoiceLine.human_attribute_name('view_invoice_line'), invoice_line %></strong></li>
              </ul>
            </div>
          </td>
          <td class='text-center'>
            <div class='dropdown'>
              <button class='btn btn-secondary btn-sm dropdown-toggle'
                type='button' id='dropdownActions<%= invoice_line.id %>'
                data-bs-toggle='dropdown' aria-expanded='false'>
                <%= translate('base.actions') %>
              </button>
              <ul class='dropdown-menu' aria-labelledby='dropdownActions<%= invoice_line.id %>'>
                <li>
                  <%= link_to invoice_line, class: 'dropdown-item' do %>
                    <i class='bi bi-eye'></i> <%= translate('actions.view') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_invoice_line_path(invoice_line), class: 'dropdown-item text-warning' do %>
                    <i class='bi bi-pencil'></i> <%= translate('actions.edit') %>
                  <% end %>
                </li>
                <li>
                  <%= link_to invoice_line, method: :delete,
                    data: { turbo_method: 'delete', turbo_confirm: turbo_confirm },
                    class: 'dropdown-item text-danger' do %>
                    <i class='bi bi-trash'></i> <%= translate('actions.delete') %>
                  <% end %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoice_lines/edit.html.erb
<%= render 'shared/header_form', record: @invoice_line %>

<%= render 'shared/record_form', record: @invoice_line %>

<%= render 'shared/footer_actions', record: @invoice_line %>

app/views/invoice_lines/index.html.erb
<div style='color: green'><%= notice %></div>

<%= render 'shared/index_header', mode: 'table' %>

<%= render 'shared/filter_form', filter_model: 'InvoiceLine' %>

<%= render 'shared/index_records', mode: 'table' %>

<%= link_to translate('base.new_record', model: InvoiceLine.model_name.human.downcase), new_invoice_line_path, class: 'btn btn-primary' %>

app/views/invoice_lines/new.html.erb
<h1>New invoice line</h1>

<%= render 'form', invoice_line: @invoice_line %>

<br>

<div>
  <%= link_to 'Back to invoice lines', invoice_lines_path %>
</div>

app/views/invoice_lines/show.html.erb
<p style='color: green'><%= notice %></p>

<%= render @invoice_line %>